name: mingw-w64 build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt install -y mingw-w64 make
          
      - name: Run build script
        run: sh run.sh

      - name: Upload Built Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: libiconv-mingw-bin
          path: libiconv-mingw-bin
